### ISSUE TITLE
Feature request -- quick option to add site to blacklist

### ISSUE THREAD

**Issue by TJMcK** [WorldBrain/Research-Engine#103] opened 2017-02-16 21:04 UTC
Really need a feature to quickly add sites to blacklist.  Either right-click menu, or option in the icon drop-down list (or both). 

And I hope there is no limit to the number of sites in the blacklist -- mine is getting big (might need a collapse option soon).

**Comment by blackforestboi** [comment] 2017-02-18 09:50
Hey @TJMcK 

Thanks for pointing this out! Its actually one of the next features we put in after we have our refactoring finished. 

I close this because its a duplicate of #46 

Soon soon :)

Have a good weekend!

**Closed as completed by blackforestboi** 2017-02-18 09:50 UTC
